apiVersion: v1
kind: Namespace
metadata:
  name: ns-new
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-new
  namespace: ns-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-new
  template:
    metadata:
      labels:
        app: deploy-new
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: '6000'
        image: quay.io/arb_khan/dev-repo:tiny-dummy-server
        name: deploy-new
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cis.f5.com/ip: 10.8.9.1
    cis.f5.com/multiClusterServices: "[\n  {\"clusterName\": \"cluster2\", \"weight\"\
      : 50},\n  {\"clusterName\": \"cluster3\", \"weight\": 30},\n  {\"clusterName\"\
      : \"cluster4\", \"weight\": 20}\n]\n"
  labels:
    app: svc-new
  name: svc-new
  namespace: ns-new
spec:
  ports:
  - name: svc-new-6000
    port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: deploy-new
  type: LoadBalancer