apiVersion: v1
kind: Service
metadata:
  labels:
    app: health-svc
  name: health-svc
  namespace: default
spec:
  ports:
  - name: svc-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: my-http-server
  sessionAffinity: None
  type: NodePort