apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster1-deploy-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster1-deploy-1
  template:
    metadata:
      labels:
        app: cluster1-deploy-1
    spec:
      containers:
        - name: cluster1-deploy-1
          image: quay.io/arb_khan/dev-repo:tiny-dummy-server
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"