apiVersion: v1
kind: Service
metadata:
  labels:
    app: cluster1-svc-1
  name: cluster1-svc-1
  namespace: default
spec:
  ports:
  - name: cluster1-svc-1-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cluster1-deploy-1
  sessionAffinity: None
  type: NodePort