apiVersion: cis.f5.com/v1
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: cr-ts-1
  namespace: ns-1
spec:
  mode: standard
  pool:
    multiClusterServices:
    # CIS supports to refer svs from local cluster and ha cluster
      - clusterName: cluster1
        namespace: default
        service: svc-1
        servicePort: 1344
        weight: 50
      - clusterName: cluster2
        namespace: default
        service: svc-2-ts-1
        servicePort: 1344
        weight: 20
      - clusterName: cluster3
        namespace: default
        service: svc-2-ts-1
        servicePort: 1344
        weight: 30
    monitor:
      interval: 20
      timeout: 10
      type: tcp
  snat: auto
  type: tcp
  virtualServerAddress: 10.8.1.1
  virtualServerPort: 1344