apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: tea-virtual-server-edge
  namespace: default
spec:
  host: tea.example.com
  httpTraffic: redirect
  virtualServerHTTPPort: 8080
  virtualServerAddress: 10.8.0.0
  pools:
    - path: /
      multiClusterServices:
        # CIS supports to refer svs from local cluster and ha cluster
        - clusterName: cluster1
          namespace: default
          service: svc-1-ts-1
          servicePort: 1344
          weight: 30
        - clusterName: cluster2
          namespace: default
          service: svc-2-ts-1
          servicePort: 1344
          weight: 20
        - clusterName: cluster3
          namespace: default
          service: svc-2-ts-1
          servicePort: 1344
          weight: 10
      monitor:
        interval: 20
        timeout: 10
        type: tcp
