apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: tea-virtual-server
  namespace: default
spec:
  virtualServerAddress: 10.8.0.4
  virtualServerHTTPPort: 8080
  partition: test
  host: tea.example.com
  pools:
    - path: /
      multiClusterServices:
        # CIS supports to refer svs from local cluster and ha cluster
        - clusterName: cluster1
          namespace: default
          service: svc-1
          servicePort: 8080
          weight: 30
        - clusterName: cluster2
          namespace: default
          service: svc-2
          servicePort: 8080
          weight: 20
        - clusterName: cluster3
          namespace: default
          service: svc-3
          servicePort: 8081
          weight: 50
      monitor:
        interval: 20
        timeout: 10
        type: tcp